var searchData=
[
  ['s_5fi5g_16963',['s_i5g',['../structs__i5g.html',1,'']]],
  ['s_5fi5g_5finit_16964',['s_i5g_init',['../structs__i5g__init.html',1,'']]],
  ['sd_5fdesc_16965',['sd_desc',['../structsd__desc.html',1,'']]],
  ['sd_5finit_5fparam_16966',['sd_init_param',['../structsd__init__param.html',1,'']]],
  ['spi_5fdesc_16967',['spi_desc',['../structspi__desc.html',1,'']]],
  ['spi_5fdevice_16968',['spi_device',['../structspi__device.html',1,'']]],
  ['spi_5fengine_5fcmd_5fqueue_16969',['spi_engine_cmd_queue',['../structspi__engine__cmd__queue.html',1,'']]],
  ['spi_5fengine_5fdesc_16970',['spi_engine_desc',['../structspi__engine__desc.html',1,'']]],
  ['spi_5fengine_5finit_5fparam_16971',['spi_engine_init_param',['../structspi__engine__init__param.html',1,'']]],
  ['spi_5fengine_5fmsg_16972',['spi_engine_msg',['../structspi__engine__msg.html',1,'']]],
  ['spi_5fengine_5foffload_5finit_5fparam_16973',['spi_engine_offload_init_param',['../structspi__engine__offload__init__param.html',1,'']]],
  ['spi_5fengine_5foffload_5fmessage_16974',['spi_engine_offload_message',['../structspi__engine__offload__message.html',1,'']]],
  ['spi_5finit_5fparam_16975',['spi_init_param',['../structspi__init__param.html',1,'']]],
  ['spi_5fplatform_5fops_16976',['spi_platform_ops',['../structspi__platform__ops.html',1,'']]],
  ['spisettings_5ft_16977',['spiSettings_t',['../structspi_settings__t.html',1,'']]],
  ['std_5ftiming_16978',['STD_TIMING',['../struct_s_t_d___t_i_m_i_n_g.html',1,'']]],
  ['strg_5ftable_16979',['STRG_TABLE',['../struct_s_t_r_g___t_a_b_l_e.html',1,'']]],
  ['synthlut_16980',['SynthLUT',['../struct_synth_l_u_t.html',1,'']]]
];
